services:
  nextjs-app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - .:/app
    command: "npm run dev"
    environment:
      - NODE_ENV=development
  