import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'primereact/resources/themes/lara-light-blue/theme.css';  
import 'primereact/resources/primereact.min.css';  
import 'primeicons/primeicons.css';
import localFont from 'next/font/local';

// const font = localFont({ src: '../../public/fonts/supermarket.woff' });
const supermarket = localFont({
  src: [
    {
      path: "../../public/fonts/supermarket.woff2", 
      weight: "400", 
      style: "normal", 
    },
  ],
  variable: "--supermarket",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${supermarket.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
